# Generated by Django 4.2.3 on 2024-05-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('tipo', models.CharField(max_length=200)),
                ('valor', models.FloatField(max_length=200)),
                ('quantidade', models.IntegerField(max_length=200)),
                ('tamanho', models.CharField(max_length=200)),
                ('data_validade', models.DateField()),
                ('data_cadastro', models.DateField()),
            ],
        ),
    ]
