# Generated by Django 4.2.3 on 2024-05-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='id',
        ),
        migrations.AlterField(
            model_name='produtos',
            name='nome',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
